{% set name = "opentypespec" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentypespec-{{ version }}.tar.gz
  sha256: 7ce1079ad942905867d63c8803e0ac1c87ee77bc773cf6fb51642c9eb5720ea6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - opentypespec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simoncozens/opentypespec-py
  summary: Data derived from the OpenType specification
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
