{% set name = "opentypespec" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentypespec-{{ version }}.tar.gz
  sha256: e63f3dacc0cac462cba0df3cfd3efe7b4c44f3f78e98a377783a56c5e9091a24

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - opentypespec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simoncozens/opentypespec-py
  summary: Data derived from the OpenType specification
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
